{% set version = "4.7.1" %}
{% set name = "libtiff" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://download.osgeo.org/{{ name }}/tiff-{{ version }}.tar.gz
    sha256: f698d94f3103da8ca7438d84e0344e453fe0ba3b7486e04c5bf7a9a3fabe9b69
    patches:
      - patches/use_unix_io.patch  # [win]

build:
  number: 1
  run_exports:
    # Does a very good job of maintaining compatibility.
    #    https://abi-laboratory.pro/tracker/timeline/libtiff/
    - {{ pin_subpackage('libtiff', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake         # [win]
    - libtool       # [unix]
    - make          # [not win]
    - ninja-base    # [win]
  host:
    - zlib {{ zlib }}
    - libjpeg-turbo {{ libjpeg_turbo }}
    - xz {{ xz }}
    - zstd {{ zstd }}
    - lerc {{ lerc }}
    - libdeflate {{ libdeflate }}
    - libwebp-base {{ libwebp_base }}  # [unix]

  run:
    - libjpeg-turbo
    - libwebp-base
    - xz
    - zlib
    - zstd
    - lerc
    - libdeflate

about:
  home: https://libtiff.gitlab.io/libtiff
  license: HPND
  license_file: LICENSE.md
  license_family: Other
  summary: Support for the Tag Image File Format (TIFF).
  description: |
    This software provides support for the Tag Image File Format (TIFF), a
    widely used format for storing image data.
  doc_url: https://libtiff.gitlab.io/libtiff
  dev_url: https://gitlab.com/libtiff/libtiff

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
