{% set version = "4.7.0" %}

package:
  name: libtiff
  version: {{ version }}

source:
  - url: https://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
    sha256: 67160e3457365ab96c5b3286a0903aa6e78bdc44c4bc737d2e486bcecb6ba976
    # folder: .
    patches:
      - patches/use_unix_io.patch  # [win]
    #   - patches/set_configure_script_version.patch  # [osx]

build:
  number: 0
  # Skip win temporarily
  # FAIL: test_directory on s390x
  skip: true  # [s390x]
  run_exports:
    # Does a very good job of maintaining compatibility.
    #    https://abi-laboratory.pro/tracker/timeline/libtiff/
    - {{ pin_subpackage('libtiff', max_pin='x') }}
  missing_dso_whitelist:
    # Only used by libtiff,bin/tiffgt (a viewer), which is ok.
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake         # [win]
    - libtool       # [unix]
    - make          # [not win]
    - ninja-base    # [win]
    - m2-patch         # [win]
  host:
    - jpeg {{ jpeg }}
    - libwebp-base {{ libwebp }} # [linux or osx]
    - xz {{ xz}}
    - zlib 1.2.13  # should be actually 1.2.11, but pinning hell
    - zstd {{ zstd }}
    - lerc 4
    - libdeflate 1.22
  run:
    - jpeg >=9e,<10a
    - libwebp-base >=1.2.4,<2.0a0 # [linux or osx]
    - xz
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
    - lerc
    - libdeflate

test:
  # test commands are moved to run_test.sh and run_test.bat
  files:
    - downstream_tests.py
    - tst_image.tif
  requires:
    - numpy
    # opencv isn't available on s390x
    - opencv  # [not s390x]
    - pillow
    - tifffile
    - imagecodecs
  # downstreams:
  #   - devil
  #   - gdk-pixbuf
  #   - geotiff
  #   - imagecodecs
  #   - lcms2
  #   - leptonica
  #   - libgd
  #   - libgdal
  #   - libwebp
  #   - opencv >=4  # [not s390x]
  #   - openjpeg
  #   - pillow >=8
  #   - poppler
  #   - poppler-qt
  #   - proj
  #   - qtimageformats
  #   - qtwebengine
  #   - vtk-base
  #   # - r-base
  #   # - r-ijtiff
  #   - opencv-python-headless  # channel sfe1ed40

about:
  home: https://libtiff.gitlab.io/libtiff
  license: HPND
  license_file: LICENSE.md
  license_family: Other
  summary: Support for the Tag Image File Format (TIFF).
  description: |
    This software provides support for the Tag Image File Format (TIFF), a
    widely used format for storing image data.
  doc_url: https://libtiff.gitlab.io/libtiff
  dev_url: https://gitlab.com/libtiff/libtiff

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
