{% set version = "4.4.0" %}

package:
  name: libtiff
  version: {{ version }}

source:
  - url: https://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
    sha256: 917223b37538959aca3b790d2d73aa6e626b688e02dcda272aec24c2f498abed
    patches:
      - patches/CVE-2022-2056.patch
    folder: .

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    # Does a very good job of maintaining compatibility.
    #    https://abi-laboratory.pro/tracker/timeline/libtiff/
    - {{ pin_subpackage('libtiff', max_pin='x') }}
  ignore_run_exports:
    - jpeg        # [win]
    - xz          # [win]
    - zlib        # [win]
    - zstd        # [win]
    - lerc        # [win]
    - libdeflate  # [win]
  missing_dso_whitelist:
    # Only used by libtiff,bin/tiffgt (a viewer), which is ok.
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake         # [win]
    - libtool       # [unix]
    - make          # [not win]
    - ninja         # [win]
    - m2-patch      # [win]
    - patch         # [not win]

  host:
    - jpeg
    - libwebp-base  # [linux or osx]
    - xz
    - zlib
    - zstd
    - lerc
    - libdeflate
  run:
    - jpeg
    - libwebp-base  # [linux or osx]
    - xz
    - zlib
    - zstd
    - lerc
    - libdeflate

test:
  downstreams:
    - pillow >=8
    - py-opencv >=4
  commands:
    - test -f ${PREFIX}/lib/libtiff.a  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx.a  # [not win]
    - test -f ${PREFIX}/lib/libtiff{{ SHLIB_EXT }}  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx{{ SHLIB_EXT }}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\tiffxx.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiffxx.dll exit 1  # [win]

about:
  # HTTPS does not work.
  home: http://www.simplesystems.org/libtiff/
  license: HPND
  license_file: COPYRIGHT
  summary: Support for the Tag Image File Format (TIFF).
  description: |
    This software provides support for the Tag Image File Format (TIFF), a
    widely used format for storing image data.
  # HTTPS does not work.
  doc_url: http://www.simplesystems.org/libtiff/
  doc_source_url: https://gitlab.com/libtiff/libtiff/-/blob/master/README.md
  dev_url: https://gitlab.com/libtiff/libtiff

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
