{% set version = "4.0.7" %}

package:
  name: libtiff
  version: {{ version }}

source:
  fn: tiff-{{ version }}.tar.gz
  url: http://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
  sha256: 9f43a2cfb9589e5cecaa66e16bf87f814c945f22df7ba600d63aac4632c4f019

build:
  number: 0
  skip: true  # [win and py35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
    - vc14  # [win and py36]

requirements:
  build:
    - python  # [win]
    - cmake  # [win]
    - toolchain
    - zlib 1.2.8
    - jpeg 9*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]
  run:
    - zlib 1.2.8
    - jpeg 9*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
    - vc 14  # [win and py36]

test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a  # [unix]
    - test -f ${PREFIX}/lib/libtiffxx.a  # [unix]
    - test -f ${PREFIX}/lib/libtiff.so  # [linux]
    - test -f ${PREFIX}/lib/libtiff.dylib  # [osx]
    - test -f ${PREFIX}/lib/libtiffxx.so  # [linux]
    - test -f ${PREFIX}/lib/libtiffxx.dylib  # [osx]
    #- conda inspect linkages -p $PREFIX libtiff  # [not win]
    #- conda inspect objects -p $PREFIX libtiff  # [osx]

about:
  home: http://www.remotesensing.org/libtiff/
  license: HPND
  license_file: COPYRIGHT
  summary: 'Support for the Tag Image File Format (TIFF).'

extra:
   recipe-maintainers:
    - jakirkham
    - ocefpaf
    - stuarteberg
