{% set version = "4.0.6" %}

package:
  name: libtiff
  version: {{ version }}

source:
  fn: tiff-{{ version }}.tar.gz
  url: http://download.osgeo.org/libtiff/tiff-4.0.6.tar.gz
  sha256: 4d57a50907b510e3049a4bba0d7888930fdfc16ce49f1bf693e5b6247370d68c
  patches:
    # http://comments.gmane.org/gmane.comp.video.tiff/6889
    - def_snprintf.patch  # [win]

build:
  number: 7
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  host:
    - zlib 1.2.*
    - jpeg 9*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]
  build:
    - cmake  # [win]
    - python  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - zlib 1.2.*
    - jpeg 9*
    - xz 5.2.*  # [not win]
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py35]

test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a  # [unix]
    - test -f ${PREFIX}/lib/libtiffxx.a  # [unix]
    - test -f ${PREFIX}/lib/libtiff.so  # [linux]
    - test -f ${PREFIX}/lib/libtiff.dylib  # [osx]
    - test -f ${PREFIX}/lib/libtiffxx.so  # [linux]
    - test -f ${PREFIX}/lib/libtiffxx.dylib  # [osx]
    #- conda inspect linkages -p $PREFIX libtiff  # [not win]
    #- conda inspect objects -p $PREFIX libtiff  # [osx]

about:
  home: http://www.libtiff.org/
  license: HPND
  license_url: http://www.libtiff.org/misc.html
  summary: 'Support for the Tag Image File Format (TIFF).'
  description: |
    This software provides support for the Tag Image File Format (TIFF), a
    widely used format for storing image data.
  doc_url: http://www.libtiff.org/document.html

extra:
   recipe-maintainers:
    - jakirkham
    - ocefpaf
    - stuarteberg
