{% set version = "4.3.0" %}
{% set build_number = "0" %}
{% set checksum = "0e46e5acb087ce7d1ac53cf4f56a09b221537fc86dfc5daaad1c2e89e1b37ac8" %}

package:
  name: libtiff
  version: {{ version }}

source:
  - url: https://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
    sha256: {{ checksum }}
    folder: .
    patches:
      - patches/fix_TIFFReadRawStrip_man_page_typo.patch
      # It seems that a recent patch in tifffile 4.1 may have broken
      # binary compatibility on windows.
      # https://gitlab.com/libtiff/libtiff/issues/173
      # https://github.com/python-pillow/Pillow/issues/4237
      - patches/use_unix_io.patch

build:
  number: {{ build_number }}
  skip: true  # [win and vc<14]
  run_exports:
    # Does a very good job of maintaining compatibility.
    #    https://abi-laboratory.pro/tracker/timeline/libtiff/
    - {{ pin_subpackage('libtiff', max_pin='x') }}
  ignore_run_exports:
    - jpeg  # [win]
  missing_dso_whitelist:
    # Only used by libtiff,bin/tiffgt (a viewer), which is ok.
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake         # [win]
    - libtool       # [unix]
    - make          # [not win]
    - ninja         # [win]
    - patch         # [not win]
    - m2-patch      # [win]
  host:
    - jpeg
    - libwebp-base  # [linux or osx]
    - xz
    - zlib
    - zstd
  run:
    - jpeg
    - libwebp-base  # [linux or osx]
    - xz
    - zlib
    - zstd

test:
  # - requires:
    # Regression testing since libtiff is only pinned to the major version.
    # See also recipe/downstream_tests.py and recipe commit bc700ad6.
    #
    # Having Python and numpy here triggers a bug in conda build, rebuilding
    # the package multiple times.
    #
    # - python 3.8  # Test with only 1 version of python
    # - numpy
    # - pillow
    #
    # - opencv  # [not s390x]
  commands:
    - test -f ${PREFIX}/lib/libtiff.a  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx.a  # [not win]
    - test -f ${PREFIX}/lib/libtiff{{ SHLIB_EXT }}  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx{{ SHLIB_EXT }}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\tiffxx.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiffxx.dll exit 1  # [win]

about:
  # HTTPS does not work.
  home: http://www.libtiff.org/
  license: HPND
  license_file: COPYRIGHT
  summary: Support for the Tag Image File Format (TIFF).
  description: |
    This software provides support for the Tag Image File Format (TIFF), a
    widely used format for storing image data.
  doc_url: http://www.libtiff.org/document.html
  dev_url: https://gitlab.com/libtiff/libtiff

extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
