{% set version = "4.0.10" %}

package:
  name: libtiff
  version: {{ version }}

source:
  url: http://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
  sha256: 2c52d11ccaf767457db0c46795d9c7d1a8d8f76f68b0b800a3dfe45786b996e4
  patches:
    - patches/fix_TIFFReadRawStrip_man_page_typo.patch
    - patches/fixed_lossless_webp_compression_config.patch

build:
  number: 1000
  # Does a very good job of maintaining compatibility.
  #    https://abi-laboratory.pro/tracker/timeline/libtiff/
  run_exports:
    - {{ pin_subpackage('libtiff', max_pin='x') }}

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - jpeg
    - xz  # [not win]
  run:
    - zlib
    - jpeg
    - xz  # [not win]

test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx.a  # [not win]
    - test -f ${PREFIX}/lib/libtiff${SHLIB_EXT}  # [not win]
    - test -f ${PREFIX}/lib/libtiffxx${SHLIB_EXT}  # [not win]

about:
  home: http://www.remotesensing.org/libtiff/
  license: HPND
  license_file: COPYRIGHT
  summary: 'Support for the Tag Image File Format (TIFF).'

extra:
   recipe-maintainers:
    - jakirkham
    - ocefpaf
    - stuarteberg
    - msarahan
