{% set version = "4.1.0" %}

package:
  name: libtiff
  version: {{ version }}

source:
  url: https://download.osgeo.org/libtiff/tiff-{{ version }}.tar.gz
  sha256: 5d29f32517dadb6dbcd1255ea5bbc93a2b54b94fbf83653b4d65c7d6775b8634
  patches:
    - patches/0003-CVE-2017-11613.patch
    - patches/fix_TIFFReadRawStrip_man_page_typo.patch

build:
  number: 1
  # This version was never built for osx-arm64.
  skip: True  # [(win and vc<14) or (osx and arm64)]
  # Does a very good job of maintaining compatibility.
  #    https://abi-laboratory.pro/tracker/timeline/libtiff/
  run_exports:
    - {{ pin_subpackage('libtiff', max_pin='x') }}
  ignore_run_exports:
    # No signs of jpeg when running dumpbin /dependents on the tiff DLLs, but
    # it's used during build, so it is probably being statically linked.
    - jpeg  # [win]
  missing_dso_whitelist:
    # Only used by libtiff,bin/tiffgt (a viewer), which is ok.
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake   # [win]
    - ninja   # [win]
    - make    # [not win]
    - patch   # [not win]
    - m2-patch  # [win]
  host:
    - zlib
    - jpeg
    - xz
    - zstd

test:
  commands:
    - test -f ${PREFIX}/lib/libtiff.a                            # [unix]
    - test -f ${PREFIX}/lib/libtiffxx.a                          # [unix]
    - test -f ${PREFIX}/lib/libtiff${SHLIB_EXT}                  # [unix]
    - test -f ${PREFIX}/lib/libtiffxx${SHLIB_EXT}                # [unix]
    - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1       # [win]
    - if not exist %PREFIX%\\Library\\bin\\tiffxx.dll exit 1     # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1    # [win]
    - if not exist %PREFIX%\\Library\\bin\\libtiffxx.dll exit 1  # [win]

about:
  home: https://libtiff.gitlab.io/libtiff/
  license: libtiff
  license_file: COPYRIGHT
  license_family: OTHER
  summary: 'Support for the Tag Image File Format (TIFF).'
  description: |
    This software provides support for the Tag Image File Format (TIFF), a
    widely used format for storing image data.
  dev_url: https://gitlab.com/libtiff/libtiff
  doc_url: http://www.simplesystems.org/libtiff/

extra:
   recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
