travis:
  secure:
    BINSTAR_TOKEN: cMw5T+QS7EAZVNuASZ23hx24oClRfsW50LJmEb9nUfD4pbmwQNh8PoFHl5Mmizv+cRBTkoyIPAA+EMUxpuYQZ+aOtEl8vmMkCFQ1/y5uXouoeWNF8vDlFx78EUnuo9/2OxYIvdYBGN3iSEDuAaZS5ABc5mRl34tJPvY2JIzoRqyhgf+voPJQA88m1WOqWMiDN6bQG4qiQVE9yIVl7Wr3n851sW+YCbfKcy45oxzUCb8M4CbCIgCcOl6zylkw5sdZ9+/kaUaDJJJx5zuEE3v8XDBqCgl6NWzSfru9XNkpsCE47MhsM6nuEL2AOusdc6e8oR0k49qvGOQ3ICVgzDtWipBCryL15BYmHkkT98rvlE/wNLnYY/MBO2lwOsaJDP/9tMH5FNJiu1gwvmP6xPHmBlJ6NgOjVxQ4CUkU/I0kbnfqCERYzRPE9RgCucVyWDv4RXauXjAD0YP3+7nq5dcUXdVbYrEejCe95RQzh2MXwCkYrCuaHUJSEeBf2dZb45J2GYpRSmpgEjaiOpIv/uD1OszSlzntsTIelBNpl5rtx5nA+dcEsZN5ibWbJyqmlbFWyz3PmBeQerfKgVdWWCusvF/GhmZjo9s6mXXKn9czy/2DrmKNeLjxZidQLAy4ry//BBq5eq7RYXfzA6sUP2JmLwMZ4eEFZ1EK8O7CeM1VhK8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
